package com.bacop.jwt_dm_project

dialect "mvel"

rule "Get Continent of Country"
when
  $co: Country($countryName:country)
  $ct: ContinentMap($continent:continent, country==$countryName)
then
  System.out.println("Country "+$countryName+" is in "+$continent);
end

rule "Apply Custom Duties to non-Europe countries"
when
  $co: Country($countryName:country)
  $ct: ContinentMap($cont:continent, $cont != "Europe", country == $countryName)
then
  insertLogical(new CustomDuties($cont,$countryName,"YES"));
end

rule "Do not apply Custom Duties to Europe countries"
when
  $co: Country($countryName:country)
  $ct: ContinentMap($cont:continent, $cont == "Europe", country == $countryName)
then
  insertLogical(new CustomDuties($cont,$countryName,"NO"));
end

