package org.pamenon.jbpm.claimfund.domain.facts;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BankDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Name of the bank or building society")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "Sort Code")
	private java.lang.Integer sortCode;
	@org.kie.api.definition.type.Label(value = "Account Number")
	private java.lang.Integer accountNumber;

	public BankDetails() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getSortCode() {
		return this.sortCode;
	}

	public void setSortCode(java.lang.Integer sortCode) {
		this.sortCode = sortCode;
	}

	public java.lang.Integer getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(java.lang.Integer accountNumber) {
		this.accountNumber = accountNumber;
	}

	public BankDetails(java.lang.String name, java.lang.Integer sortCode,
			java.lang.Integer accountNumber) {
		this.name = name;
		this.sortCode = sortCode;
		this.accountNumber = accountNumber;
	}

}