package org.pamenon.jbpm.claimfund.domain.facts;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Farm implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Business Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("type")
	private java.lang.String type;
	@org.kie.api.definition.type.Label("size")
	private java.lang.Integer size;

	public Farm() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.Integer getSize() {
		return this.size;
	}

	public void setSize(java.lang.Integer size) {
		this.size = size;
	}

	public Farm(java.lang.String name, java.lang.String type,
			java.lang.Integer size) {
		this.name = name;
		this.type = type;
		this.size = size;
	}

}