package org.pamenon.jbpm.claimfund.domain.facts;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Loan implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Amount of Loan")
	private Long amount;
	@org.kie.api.definition.type.Label("Reason")
	private java.lang.String reason;

	public Loan() {
	}

	public java.lang.String getReason() {
		return this.reason;
	}

	public void setReason(java.lang.String reason) {
		this.reason = reason;
	}

	public java.lang.Long getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Long amount) {
		this.amount = amount;
	}

	public Loan(java.lang.Long amount, java.lang.String reason) {
		this.amount = amount;
		this.reason = reason;
	}

}