name: Build for pam-eap-setup.

on:
  push:
    paths:
      - .github/workflows/build-pam-eap-setup.yaml
      - pam-eap-setup/**
  pull_request:
    paths:
      - .github/workflows/build-pam-eap-setup.yaml
      - pam-eap-setup/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore: bcgithook bdd-ui kogito-quick-start-workshop offliner-maven-plugin pam-quick-examples