name: Build for pam-eap-setup

on:
  push:
    paths:
      - .github/workflows/build-pam-eap-setup.yaml
      - pam-eap-setup/**
  pull_request:
    paths:
      - .github/workflows/build-pam-eap-setup.yaml
      - pam-eap-setup/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: redhat-csp-download
        if: matrix.os == 'ubuntu-latest'
        uses: garethahealy/github-actions/redhat-csp-download@master
        with:
          rh_username: ${{ secrets.RH_USERNAME }}
          rh_password: ${{ secrets.RH_PASSWORD }}
          download: '[{"file":"/github/workspace/pam-eap-setup/jboss-eap-7.2.0.zip","url":"https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId=64311"},{"file":"/github/workspace/pam-eap-setup/jboss-eap-7.2.8-patch.zip","url":"https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId=81791"},{"file":"/github/workspace/pam-eap-setup/rhpam-7.7.1-business-central-eap7-deployable.zip","url":"https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId=82441"},{"file":"/github/workspace/pam-eap-setup/rhpam-7.7.1-kie-server-ee8.zip","url":"https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId=82291"}]'

      - name: Run pam-setup.sh
        if: matrix.os == 'ubuntu-latest'
        uses: ./.github/actions/eap-base
        with:
          should_run: ${{ secrets.RH_USERNAME }}
          command: "cd pam-eap-setup; ./pam-setup.sh; rm -rf pam"

      - name: Run ShellCheck
        if: matrix.os == 'ubuntu-latest'
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error
          ignore: bcgithook bdd-ui kogito-quick-start-workshop offliner-maven-plugin pam-quick-examples pam-vagrant
