# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven for offliner-maven-plugin

on:
  push:
    paths:
      - .github/workflows/mvn-offliner-maven-plugin.yaml
      - offliner-maven-plugin/**
  pull_request:
    paths:
      - .github/workflows/mvn-offliner-maven-plugin.yaml
      - offliner-maven-plugin/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-offliner-maven-plugin-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build offliner-maven-plugin
        run: mvn -B clean install -f offliner-maven-plugin/pom.xml --no-transfer-progress